AllCops:
  TargetRubyVersion: 2.6.4
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*.rb
    - lib/**/*
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
    - bin/**/*
    - config/**/*

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/MixinUsage:
  Exclude:
    - bin/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Exclude:
    - config/**/*.rb
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/initializers/*.rb'
    - 'config/routes.rb'
    - config/environments/*.rb
    - '**/concerns/*.rb'
