# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2.3.5

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.4-node-browsers
        environment:
          BUNDLER_VERSION: 2.1.2
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
      - image: circleci/mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: <%= ENV["DATABASE_PASSWORD"] %>
          MYSQL_DATABASE: Currency_test
          MYSQL_USER: root
          MYSQL_PASSWORD: <%= ENV["DATABASE_PASSWORD"] %>

    working_directory: ~/Currency

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: bundler-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install dependencies
          command: |
            gem install bundler:2.1.2
            gem install rubocop
            bundle config --local frozen true
            bundle config --local without production:development:staging
            bundle config --local path vendor/bundle
            bundle check || bundle install --jobs=4 --retry=3

      - save_cache:
          key: bundler-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Rubocop
          command: |
            mkdir /tmp/rubocop
            bundler exec rubocop --format html --out /tmp/rubocop/results.html

      # collect reports
      - store_artifacts:
          path: /tmp/rubocop
          destination: rubocop
